---
title: "Custom-numbered-blocks Example"
number-sections: true
filters:
  - custom-numbered-blocks
format:
  html: default
  #pdf: default 
  #native: default

custom-numbered-blocks:
  styles:  
    default:
      boxtype: foldbox #fallback
    #   colors: [ffffff,aaaaaa] 
    postit:
      boxtype: simpletextbox
      color: green 
    mixmax:
      boxtype: foldbox
      colors: [aaaaaa, '040404'] 
    quatsch:  
      parent: postit
      color: blue
      numbered: false
    quietsch:  
      color: quietschgruen
    # default may not have a parent!  
  groups:
    todos: # default  
      numbered: false
      #style: mixmax 
   #   style: postit 
   #   boxtype: fallback 
    mathstuff: default
    BLOWDZINN:
      numbered: false
      style: postit
      color: red
      zinn: bloed    
  classes:    
    TODO:
   #   style: postit
    #  boxtype: fallback
      collapse: false
      # numbered: true
      #boxtype: foldblock
      label: "To do"
      group: todos
    NixDo: default
    Theorem:
      group: mathstuff

crossref:
  chapters: true
---

::: TODO
### simpletextbox

- [x] make referenceable - this works out of the box, I was sooo clever with the design ;-)
:::
Strange enough, it seems I do not need the hand made ankers in pdf anymore?

Hier kommt nothing: \longref{nuttin}

# First heading

Do not allow `div` elements to change boxtype or colours. This is due to the implementations.

::: {.NixDo collapse=true}
### Change *internal* registration of Divs {#firsta}
This is relatively epic
:::


::: {.TODO boxtype="foldbox" collapse="false" label="ZuTun" tag= "x" style="mixmax" #foerst }
### Change internal registration of Divs
This is relatively epic

- [x] do not use div attributes, but an internal table
  - [x] set up the table in parallel
    - [x] make identifiers for all divs
    - [x] add to cnbx.customblocks. However did this in xref 
    - [ ] Catch error: duplex
  - [x] test by inspection
  - [x] change how styles use the information
    - [x] start with fallbackexample
    - [x] test fallbackexample 
  - [ ] check if lists-of still are working. Now use mdtitle - maybe I already do this.

:::

::: {.DONE title = "not ywt done"}

All is done

:::

::: TODO
The div with no title
:::

# second heading

::: {.NixDo label="Nixtun"}
# this is only for testing purposes {#second}

For example, to catch duplex identifiers
:::

::: {.TODO .unnumbered}
# crossreferencing using pandoc
An epic one, to enable independence of formats.
Let's see if this is possible. A future thing.
:::


Und jetzt weisen wir noch hin auf das Todo first: \longref{foerst}

And now cnb-4-TODO: \longref{cnb-4-TODO}